#if !canImport(ObjectiveC)
import XCTest

extension GzipperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GzipperTests = [
        ("testCompressionDecompression_whenCompressionTypeLz4_shouldReturnOriginalData", testCompressionDecompression_whenCompressionTypeLz4_shouldReturnOriginalData),
        ("testCompressionDecompression_whenCompressionTypeLzfse_shouldReturnOriginalData", testCompressionDecompression_whenCompressionTypeLzfse_shouldReturnOriginalData),
        ("testCompressionDecompression_whenCompressionTypeLzma_shouldReturnOriginalData", testCompressionDecompression_whenCompressionTypeLzma_shouldReturnOriginalData),
        ("testCompressionDecompression_whenCompressionTypeZlib_shouldReturnOriginalData", testCompressionDecompression_whenCompressionTypeZlib_shouldReturnOriginalData),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GzipperTests.__allTests__GzipperTests),
    ]
}
#endif
