name: ci-library-zipper-ios

on:
  pull_request:
    branches: [ main ]

jobs:
  test-library-zipper-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
