name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: krzyzanowskim/CryptoSwift
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
